services:
  queue:
    image: redis:latest

  web:
    build:
      ./web
    ports:
      - 80:80
    depends_on:
      - delivery
      - processing

  delivery:
    build:
      ./delivery
    volumes:
      - videos-vol:/videos
    ports:
      - 3000:80
    depends_on:
      - queue

  processing:
    build:
      ./processing
    volumes:
      - videos-vol:/videos
    depends_on:
      - queue

volumes:
  videos-vol: